### ISSUE TITLE
Generate List of used Images by Kubify

### ISSUE THREAD

**Issue by afritzler** [gardener/kubify#30]
Create a script to extract images used by Kubify. Ideally we generate a file out of it and keep it in the repository.

**Comment by vlerenc** [comment]
Yes, I believe this could help PM very much.

It could be integrated into the CI/CD release build, but what's that for Kubify? Since there is nothing to be compiled or imaged, it would be only doing the bump commits and release tagging, telling the users that a new version is ready for consumption. OK?

Once you have that (which shouldn't be much effort at all), a pre-release step or general step could update the BoM automatically and generate a list similar to the [Gardener](https://github.com/gardener/gardener/blob/master/charts/images.yaml). Technically the processes differ (in Gardner everything is configured there and used elsewhere, while in Kubify everything is in Terraform modules and extracted later), but from PM's PoV it doesn't matter.

However, it's hard to find all locations. Sometimes also variables are used, so you won't find these locations easily respectively there is only a variable reference behind `image:`, but you will know better how to extract them all.

**Comment by afritzler** [comment]
As a quick fix for now: you can extract all used images with their corresponding tags by:
```
cd gen
grep -R "image:"
```

**Comment by afritzler** [comment]
Fixed with bfb174c943c4e126227f6e63956c17d540f56250
